const actionType = {
  POKELIST_FETCH: "POKELIST/FETCH",
  URL_SET: "URL/SET",
  NEXTURL_SET: "NEXTURL/SET",
  PREVURL_SET: "PREVURL/SET",
  NAVIGATE_NEXT: "NAVIGATE/NEXT",
  NAVIGATE_PREV: "NAVIGATE/PREV",
  POKEMON_SEARCH: "POKEMON/SEARCH",
};

export const POKELIST_FETCH = "POKELIST/FETCH"
export const URL_SET = "URL/SET"
export const NEXTURL_SET = "NEXTURL/SET"
export const PREVURL_SET = "PREVURL/SET"
export const NAVIGATE_NEXT = "NAVIGATE/NEXT"
export const NAVIGATE_PREV = "NAVIGATE/PREV"
export const POKEMON_SEARCH = "POKEMON/SEARCH"