const actionType = {
  POKEMON_BIO: "POKEMON/BIO",
  POKEMON_WEIGHT: "POKEMON/WEIGHT",
  POKEMON_HEIGHT: "POKEMON/HEIGHT",
  POKEMON_ABILITIES: "POKEMON/ABILITIES",
  POKEMON_HP: "POKEMON/HP",
  POKEMON_ATTACK: "POKEMON/ATTACK",
  POKEMON_DEFENSE: "POKEMON/DEFENSE",
  POKEMON_SPATTACK: "POKEMON/SPATTACK",
  POKEMON_SPDEFENSE: "POKEMON/SPDEFENSE",
  POKEMON_SPEED: "POKEMON/SPEED"
};

export const POKEMON_BIO = "POKEMON/BIO"
export const POKEMON_WEIGHT = "POKEMON/WEIGHT"
export const POKEMON_HEIGHT = "POKEMON/HEIGHT"
export const POKEMON_ABILITIES = "POKEMON/ABILITIES"
export const POKEMON_HP = "POKEMON/HP"
export const POKEMON_ATTACK = "POKEMON/ATTACK"
export const POKEMON_DEFENSE = "POKEMON/DEFENSE"
export const POKEMON_SPATTACK = "POKEMON/SPATTACK"
export const POKEMON_SPDEFENSE = "POKEMON/SPDEFENSE"
export const POKEMON_SPEED = "POKEMON/SPEED"